version: '2'
services:
  cassandra:
    image: mashape/cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra
  cassandra1:
    image: mashape/cassandra
    links:
      - cassandra:seed
    environment:
      CASSANDRA_SEEDS: seed
  cassandra2:
    image: mashape/cassandra
    links:
      - cassandra:seed
    environment:
      CASSANDRA_SEEDS: seed

  kong:
    image: mashape/kong
    networks:
      - cassandra
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    command: ["/bin/bash", "-c", " while ! nc cassandra 9042; do sleep 5; done && kong start && tail -f /usr/local/kong/logs/error.log"]
  kong2:
    image: mashape/kong
    networks:
      - cassandra
    command: ["/bin/bash", "-c", " while ! nc cassandra 9042; do sleep 5; done && kong start && tail -f /usr/local/kong/logs/error.log"]

  ui:
    image: pgbi/kong-dashboard
    container_name: kong_ui
    ports:
      - "8080:8080"

networks:
  cassandra:
    driver: bridge
