version: '2'
services:
  cassandra:
    image: mashape/cassandra
    networks:
      - cassandra
    ports:
      - "9042:9042"

  kong:
    image: mashape/kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    networks:
      - cassandra
    depends_on:
      - cassandra
    restart: always

networks:
  cassandra:
    driver: bridge
